name: default
on: push
jobs:
  example:
    name: ltk-gem-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby_version: '2.6'
      - name: install_bundler
        run: gem install bundler:1.17.2
      - name: install_bundle
        run: gem install bundle
      - name: install_dependencies
        run: bundle install
