name: default
on: push
defaults:
  run: 
    shell: bash
    working-directory: scripts
jobs:
  example:
    name: ltk-gem-example-job
    runs-on: centos-latest
    steps:
      - id: one
        run: init.sh
