name: default
on: push
jobs:
  example:
    name: ltk-gem-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby_version: '2.6'
      - name: make gem directory
        run: 'mkdir -p ~/.gem'
      - name: credentials
        run: 'echo ":github: Bearer ${{secrets.LTK_GITHUB_TOKEN}}" >> ~/.gem/credentials'
      - name: correct_permissions
        run: 'chmod 600 ~/.gem/credentials'
      - name: install_bundler
        run: gem install bundler:1.17.2
      - name: install_bundle
        run: gem install bundle
      - name: install_dependencies
        run: bundle install
      - name: test
        run: rake test
      - name: build
        run: rake build
      - name: print token
        run: 'cat ~/.gem/credentials'
      - name: push package
        run: gem push --key github --host https://rubygems.pkg.github.com/luisfelipemourapereira pkg/ltk-gem-0.0.1.gem
